services:
  open-webui:
    ports:
      - 8080:8080

  n8n:
    ports:
      - 5678:5678

  qdrant:
    ports:
      - 6333:6333
      - 6334:6334

  neo4j:
    ports:
      - 7473:7473
      - 7474:7474
      - 7687:7687

  redis:
    ports:
      - 6379:6379

  searxng:
    ports:
      - 8081:8080

  ollama-cpu:
    ports:
      - 11434:11434

  caddy:
    ports:
      - 80:80
      - 443:443
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 1.1.1.1
      - 8.8.8.8

networks:
  default:
    name: localai_default
    external: true
